/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#002046",
        "primary-container": "#1b365d",
        "on-primary": "#ffffff",
        "on-primary-container": "#87a0cd",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#aec7f7",
        "on-primary-fixed": "#001b3d",
        "on-primary-fixed-variant": "#2e476f",
        "inverse-primary": "#aec7f7",

        "secondary": "#006399",
        "secondary-container": "#67bafd",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#004972",
        "secondary-fixed": "#cde5ff",
        "secondary-fixed-dim": "#94ccff",
        "on-secondary-fixed": "#001d32",
        "on-secondary-fixed-variant": "#004b74",

        "tertiary": "#1d2123",
        "tertiary-container": "#333638",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#9c9fa1",
        "tertiary-fixed": "#e0e3e5",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-tertiary-fixed": "#191c1e",
        "on-tertiary-fixed-variant": "#444749",

        "surface": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "surface-variant": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#44474e",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        "surface-tint": "#465f88",

        "background": "#f8f9ff",
        "on-background": "#0b1c30",

        "outline": "#74777f",
        "outline-variant": "#c4c6cf",

        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        "alert-critical": "#dc2626",
        "alert-critical-bg": "#fef2f2",
        "alert-warning": "#d97706",
        "alert-warning-bg": "#fffbeb",
        "alert-recovery": "#059669",
        "alert-recovery-bg": "#ecfdf5",
        "accent-green": "#059669",
        "accent-orange": "#d97706",
        "ai-accent": "#7c3aed",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "20px",
        margin: "24px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"],
      },
      boxShadow: {
        sm: "0 1px 2px 0 rgba(27, 54, 93, 0.05)",
        DEFAULT: "0 1px 3px 0 rgba(27, 54, 93, 0.08), 0 1px 2px -1px rgba(27, 54, 93, 0.08)",
        md: "0 4px 6px -1px rgba(27, 54, 93, 0.08), 0 2px 4px -2px rgba(27, 54, 93, 0.08)",
        lg: "0 10px 15px -3px rgba(27, 54, 93, 0.08), 0 4px 6px -4px rgba(27, 54, 93, 0.08)",
        ambient: "0 4px 20px -2px rgba(27, 54, 93, 0.06)",
        hover: "0 8px 30px rgba(27, 54, 93, 0.12)",
      },
    },
  },
  plugins: [],
};
